## jekyll config options
title : John Stanton-Geddes
exclude : [_posts/_private/, assets/figures, _posts/Rmd_cache/]

## metadata
author :
  name : John Stanton-Geddes
  email : john.stantongeddes.research@gmail.com
  github : johnstantongeddes
  mendeley: john-stantongeddes
url: http://www.johnstantongeddes.org

baseurl : 

## markdown parser
markdown : pandoc
pandoc:
  format: html5
  extensions: 
    - smart
    - mathjax
#    - csl: '
#    - bibliography: 'references.bib'
