---
layout: posts
category: ecological genetics
title: Reviews
tags:
  - service
  - open science
modified: 2013-10-29
---

**Table of reviews in status and completed.** Mostly for my own tracking of 'service' to the community. I've archived all these reviews and will make them available upon request (and journal guidelines - does anyone know if there are restrictions on this?). 

```{r, echo=FALSE}
days = c(9, 3, 10, 8, 4, 11)
```

The "Date Accepted" and "Date Completed" are a public guilt-trip to complete reviews on time, which I started tracking October 2013. As of October 2013, my time average time to completion for reviews is `r sum(days)/length(days)` (working) days. 


| Year | Journal | Re-review? | Date Accepted | Date Completed |
|:-----|:-------:|:----------:|:-------------:|:--------------:|
| 2014 | PLoS ONE | Yes | 2014-04-11 | In progress |
| 2014 | PLoS Biology | No | 2014-04-09 | In progress |
| 2014 | Ecological Monographs | Yes | 2014-03-31 | 2014-04-14 |
| 2014 | Molecular Ecology | No | 2014-02-21 | 2014-02-27 |
| 2014 | PLoS ONE | No | 2014-01-06 | 2014-01-20 |
| 2014 | Ecology Letters | Yes | 2014-01-01 | 2013-01-06 |
| 2013 | Ecology Letters | No | 2013-10-10 | 2013-10-23 |
| 2013 | Evolution | Yes | na | Completed |
| 2013 | Ecological Monographs | No | na | Completed |
| 2013 | Proceedings B | No | na | Completed |
| 2013 | Journal of Forest Reseach | No | na | Completed |
| 2013 | Evolution | No | na | Completed |
| 2013 | Functional Ecology | No | na | Completed |
| 2013 | Global Change Biology | Yes | na | Completed |
| 2012 | Journal of Forest Research | Yes | na | Completed |
| 2012 | Evolution | No | na | Completed |
| 2012 | Journal of Forest Research | No | na | Completed |
| 2012 | Evolutionary Ecology | No | na | Completed |
| 2012 | Global Change Biology | No | na | Completed |
| 2012 | Oikos | No | na | Completed |
| 2011 | Oecologia | No | na | Completed |
| 2011 | International Journal of Plant Sciences | No | na | Completed |
| 2011 | Journal of Plant Interactions | No | na | Completed |
| 2011 | American Journal of Botany | No | na | Completed |
| 2011 | Evolution | No | na | Completed |

