---
layout: posts
categories: ApTranscriptome ApGXL
title: Monday notes
tags: 
  - pander
  - review
---

* Finished review for PLoS ONE
* MolEcologist Q&A with Pleuni Pennings scheduled
* Test to add R knitting functionality to lab notebook
   - allows evaluating R math and plots
   - use [knitcitations] for references instead of copy paste

http://stackoverflow.com/questions/4696128/bash-script-determine-if-file-modified

### ApThermBe

Ideas for laser-trip camera [here](http://yourduino.com/sunshop2/index.php?l=product_detail&p=47), [here](http://bildr.org/2012/11/photoresistor-arduino/) and [here](http://www.instructables.com/id/Arduino-Laser-System-Tripwire-Tutorial/)

Or maybe a [simple time-delay](http://timmsuess.com/projects/intervaluino/)

### ApGXL

Bioanalyzer results from last week's extractions. 

```{r, echo=FALSE, results="asis"}
library(pander)
panderOptions("table.split.table", Inf)

Sample <- c('RQ3-1', 'RQ1-1', 'RQ3-2', 'RQ1-2', 'RQ3-3', 'RQ1-3', 'RQ3-1', 'RQ1-1', 'RQ3-2', 'RQ1-2', 'RQ3-3', 'RQ1-3', 'Q1-1', 'Q1-2', 'Q1-3')
Colony <- c("2012 A1", "2012 A1", "EW200", "EW200", "EW1000", "EW1000", "2012 A1", "2012 A1", "EW200", "EW200", "EW1000", "EW1000", "2012 A1", "EW200", "EW1000")
Num_ants <- c(rep(c(3,1), 6), rep(1, 3))
Extraction <- c(rep('R', 6), rep('R+Q', 6), rep('Q', 3))
Nano_conc <- c(31.6, 13.9, 26.6, 16.2, 60.3, 21.4, 18.9, 0.7, 0.7, 5.9, 5.5, 1.6, 3.8, 2.1, 3.5)
Nano_qual <- c(1.6, 1.7, 1.8, 1.9, 1.7, 1.6, 2.1, NA, 0.9, 0.5, 3.0, 1.6, 2.0, 1.6, 2.3)
Bio_conc <- c(0.1, 0.7, 1.9, 1.4, 7.4, 5.1, 7.6, NA, NA, NA, 5.7, NA, 1.7, NA, NA)
RIN <- c(2.7, 8.8, 7.5, 7.1, 9.6, 9.5, 5.9, NA, NA, NA, 9.7, NA, 7.7, NA, NA)

rnatable <- cbind(Sample, Colony, Num_ants, Extraction, Nano_conc, Nano_qual, Bio_conc, RIN)

pandoc.table(rnatable, style="rmarkdown", caption = "Nanodrop and Bioanalyzer results for different RNA extraction methods. Concentration in ng/ul. Extraction: R = RNAzol; R+Q = RNAzol + RNeasy; Q = RNeasy. Note that all Qiagen samples were first accidentally eluted in 170 ul and then re-precipitated using column into 17 ul.")
```

Notes:

* RNAzol only (R) extraction gives RIN adequate for DGE (> 7)
* RNAzol elution in 100 ul gives about 100 ng 
* Nanodrop overestimates concentration by an order of magnitude
* Nanodrop 260/280 not indicative of RIN (e.g RQ3-1 260/280 = 1.6 while RIN = 2.7)

Based on these extractions, use RNAzol extraction only (no RNeasy) for ApGXL samples. 
Elute in 25 ul to concentrate RNA for DGE.


--------------------------------------------------------------------------------------

New set of RNA extractions 

- 3 Phytotron samples
- 3 lab ants

All 6 through RNAzol. Take aliquots for Bioanalyzer. Reserve 100 ng from RNAzol step for Phytotron samples and run remainig sample through RNeasy. Send 9 samples to Bioanalyzer.

### ApTranscriptome

Updated code to output P-values, Q-values and coefficients for significant linear and quadratic terms for each transcripts
